/**
 * src/convictions.js
 * Generated by tools/populate-packs.mjs from PHB 3.4.1-3.4.4. Do not edit by hand.
 */

export const CONVICTIONS = {
  "faith": [
    {
      "roll": 1,
      "trait": "I offer strangers the benefit of the doubt before they've earned it.",
      "lean": "high"
    },
    {
      "roll": 2,
      "trait": "I believe most people are doing their best with what they've got.",
      "lean": "high"
    },
    {
      "roll": 3,
      "trait": "I take a promise at face value until it's broken, not before.",
      "lean": "high"
    },
    {
      "roll": 4,
      "trait": "I lend before I'm asked twice.",
      "lean": "high"
    },
    {
      "roll": 5,
      "trait": "I check the exits before I check the menu.",
      "lean": "low"
    },
    {
      "roll": 6,
      "trait": "I keep something back in every deal, just in case.",
      "lean": "low"
    },
    {
      "roll": 7,
      "trait": "I read a friendly face as a mask until it's proven otherwise.",
      "lean": "low"
    },
    {
      "roll": 8,
      "trait": "I trust what I can verify, not what I'm told.",
      "lean": "low"
    },
    {
      "roll": 9,
      "trait": "I trust people slowly, in proportion to what they've actually shown me.",
      "lean": "neutral"
    },
    {
      "roll": 10,
      "trait": "Whether I trust you depends entirely on what's at stake.",
      "lean": "neutral"
    }
  ],
  "order": [
    {
      "roll": 1,
      "trait": "I keep my gear in the same place every time, so I can find it in the dark.",
      "lean": "high"
    },
    {
      "roll": 2,
      "trait": "I think a plan beats improvising, nine times out of ten.",
      "lean": "high"
    },
    {
      "roll": 3,
      "trait": "Rules exist because someone already learned the hard way; I'd rather not relearn it.",
      "lean": "high"
    },
    {
      "roll": 4,
      "trait": "I'd rather lose by the rules than win by breaking them.",
      "lean": "high"
    },
    {
      "roll": 5,
      "trait": "I've never met a plan that survived contact with anything.",
      "lean": "low"
    },
    {
      "roll": 6,
      "trait": "Rules are the first thing to go when it actually matters.",
      "lean": "low"
    },
    {
      "roll": 7,
      "trait": "I leave a mess and let tomorrow deal with it.",
      "lean": "low"
    },
    {
      "roll": 8,
      "trait": "I'll break a promise the moment keeping it stops making sense.",
      "lean": "low"
    },
    {
      "roll": 9,
      "trait": "Rules are tools, not commandments; I use the ones that work.",
      "lean": "neutral"
    },
    {
      "roll": 10,
      "trait": "I plan for the big things and improvise the rest.",
      "lean": "neutral"
    }
  ],
  "individualism": [
    {
      "roll": 1,
      "trait": "I look out for myself first; I can't help anyone if I'm the one who falls.",
      "lean": "high"
    },
    {
      "roll": 2,
      "trait": "I'd rather succeed alone than share credit for a group effort.",
      "lean": "high"
    },
    {
      "roll": 3,
      "trait": "My goals come before the group's, when they conflict.",
      "lean": "high"
    },
    {
      "roll": 4,
      "trait": "I take what I've earned and don't feel guilty about it.",
      "lean": "high"
    },
    {
      "roll": 5,
      "trait": "I'll go hungry before the group does.",
      "lean": "low"
    },
    {
      "roll": 6,
      "trait": "My word to the group outweighs my own preference every time.",
      "lean": "low"
    },
    {
      "roll": 7,
      "trait": "I've given up things I wanted because the group needed them more.",
      "lean": "low"
    },
    {
      "roll": 8,
      "trait": "I put myself between danger and whoever's behind me, without being asked.",
      "lean": "low"
    },
    {
      "roll": 9,
      "trait": "I look out for myself and the group in equal measure, no more for either.",
      "lean": "neutral"
    },
    {
      "roll": 10,
      "trait": "I share what I don't need and keep what I do.",
      "lean": "neutral"
    }
  ],
  "levity": [
    {
      "roll": 1,
      "trait": "I make a joke out of whatever's trying to crush me.",
      "lean": "high"
    },
    {
      "roll": 2,
      "trait": "I'd rather defuse a tense moment with a laugh than let it sit.",
      "lean": "high"
    },
    {
      "roll": 3,
      "trait": "I tease the people I care about; it's how I say it without saying it.",
      "lean": "high"
    },
    {
      "roll": 4,
      "trait": "I take the work seriously and myself not at all.",
      "lean": "high"
    },
    {
      "roll": 5,
      "trait": "I've stopped finding most things funny, and I'm not sorry about it.",
      "lean": "low"
    },
    {
      "roll": 6,
      "trait": "I carry what's happened to me; I don't set it down to make room for a laugh.",
      "lean": "low"
    },
    {
      "roll": 7,
      "trait": "I don't perform lightness I don't feel.",
      "lean": "low"
    },
    {
      "roll": 8,
      "trait": "Silence sits easier with me than small talk.",
      "lean": "low"
    },
    {
      "roll": 9,
      "trait": "I laugh when it's earned and stay quiet when it isn't.",
      "lean": "neutral"
    },
    {
      "roll": 10,
      "trait": "Some days are lighter than others, and I let them be.",
      "lean": "neutral"
    }
  ]
};
