/** Generated by tools/build-creature-data.mjs from the GMG (9.5.0, 9.5.1, 9.6.1). Do not edit. */
export const NATURAL_WEAPONS = [
 {
  "name": "Claws",
  "group": "melee",
  "types": [
   "edged"
  ],
  "pick": false,
  "range": "Touching to Close"
 },
 {
  "name": "Spines",
  "group": "melee",
  "types": [
   "edged"
  ],
  "pick": false,
  "range": "Touching to Close"
 },
 {
  "name": "Bite",
  "group": "melee",
  "types": [
   "pointed"
  ],
  "pick": false,
  "range": "Touching"
 },
 {
  "name": "Tusks",
  "group": "melee",
  "types": [
   "pointed"
  ],
  "pick": false,
  "range": "Touching"
 },
 {
  "name": "Beak",
  "group": "melee",
  "types": [
   "pointed"
  ],
  "pick": false,
  "range": "Touching"
 },
 {
  "name": "Stinger",
  "group": "melee",
  "types": [
   "pointed"
  ],
  "pick": false,
  "range": "Touching"
 },
 {
  "name": "Proboscis",
  "group": "melee",
  "types": [
   "pointed"
  ],
  "pick": false,
  "range": "Touching"
 },
 {
  "name": "Pharyngeal Jaw",
  "group": "melee",
  "types": [
   "pointed"
  ],
  "pick": false,
  "range": "Touching"
 },
 {
  "name": "Horns",
  "group": "melee",
  "types": [
   "blunt",
   "pointed"
  ],
  "pick": true,
  "range": "Touching to Close"
 },
 {
  "name": "Hooves",
  "group": "melee",
  "types": [
   "blunt"
  ],
  "pick": false,
  "range": "Touching"
 },
 {
  "name": "Crushing Jaws",
  "group": "melee",
  "types": [
   "blunt"
  ],
  "pick": false,
  "range": "Touching"
 },
 {
  "name": "Slam",
  "group": "melee",
  "types": [
   "blunt"
  ],
  "pick": false,
  "range": "Touching to Close"
 },
 {
  "name": "Tail Strike",
  "group": "melee",
  "types": [
   "blunt",
   "edged"
  ],
  "pick": true,
  "range": "Close"
 },
 {
  "name": "Pincers",
  "group": "melee",
  "types": [
   "blunt",
   "edged"
  ],
  "pick": true,
  "range": "Touching to Close"
 },
 {
  "name": "Wing Buffet",
  "group": "melee",
  "types": [
   "blunt"
  ],
  "pick": false,
  "range": "Close"
 },
 {
  "name": "Barbed Whip",
  "group": "melee",
  "types": [
   "edged"
  ],
  "pick": false,
  "range": "Close"
 },
 {
  "name": "Tentacles",
  "group": "grappling",
  "types": [
   "grappling"
  ],
  "pick": false,
  "range": "Near"
 },
 {
  "name": "Tongue-Lash",
  "group": "grappling",
  "types": [
   "grappling"
  ],
  "pick": false,
  "range": "Near"
 },
 {
  "name": "Coils",
  "group": "grappling",
  "types": [
   "grappling"
  ],
  "pick": false,
  "range": "Touching"
 },
 {
  "name": "Maw",
  "group": "grappling",
  "types": [
   "grappling"
  ],
  "pick": false,
  "range": "Touching"
 },
 {
  "name": "Sticky Secretion",
  "group": "grappling",
  "types": [
   "grappling"
  ],
  "pick": false,
  "range": "Touching"
 },
 {
  "name": "Many Limbs",
  "group": "grappling",
  "types": [
   "grappling"
  ],
  "pick": false,
  "range": "Touching"
 },
 {
  "name": "Prehensile Tail",
  "group": "grappling",
  "types": [
   "grappling"
  ],
  "pick": false,
  "range": "Close"
 },
 {
  "name": "Gripping Claw",
  "group": "grappling",
  "types": [
   "grappling"
  ],
  "pick": false,
  "range": "Touching to Close"
 },
 {
  "name": "Web",
  "group": "grappling",
  "types": [
   "grappling",
   "thrown"
  ],
  "pick": false,
  "range": "Short"
 },
 {
  "name": "Breath Weapon",
  "group": "arcane",
  "types": [
   "kinetic"
  ],
  "pick": false,
  "range": "Short to Mid"
 },
 {
  "name": "Acid Sac",
  "group": "arcane",
  "types": [
   "kinetic"
  ],
  "pick": false,
  "range": "Short to Mid"
 },
 {
  "name": "Spore Cloud",
  "group": "arcane",
  "types": [
   "kinetic"
  ],
  "pick": false,
  "range": "Close"
 },
 {
  "name": "Static Field",
  "group": "arcane",
  "types": [
   "kinetic"
  ],
  "pick": false,
  "range": "Close"
 },
 {
  "name": "Evil Eye",
  "group": "arcane",
  "types": [
   "incorporeal"
  ],
  "pick": false,
  "range": "Sight"
 },
 {
  "name": "Mind Lash",
  "group": "arcane",
  "types": [
   "incorporeal"
  ],
  "pick": false,
  "range": "Mid"
 },
 {
  "name": "Chilling Presence",
  "group": "arcane",
  "types": [
   "incorporeal"
  ],
  "pick": false,
  "range": "Close"
 },
 {
  "name": "Curse Touch",
  "group": "arcane",
  "types": [
   "incorporeal"
  ],
  "pick": false,
  "range": "Touching"
 },
 {
  "name": "Siphoning Maw",
  "group": "arcane",
  "types": [
   "incorporeal"
  ],
  "pick": false,
  "range": "Touching"
 },
 {
  "name": "Life-Fount",
  "group": "arcane",
  "types": [
   "fortifying"
  ],
  "pick": false,
  "range": "Near"
 },
 {
  "name": "Ward-Hide",
  "group": "arcane",
  "types": [
   "blocking",
   "fortifying"
  ],
  "pick": false,
  "range": "Touching"
 },
 {
  "name": "Bone-Trumpet",
  "group": "sonic",
  "types": [
   "sonic"
  ],
  "pick": false,
  "range": "Long"
 },
 {
  "name": "Roar",
  "group": "sonic",
  "types": [
   "sonic"
  ],
  "pick": false,
  "range": "Mid"
 },
 {
  "name": "Shriek",
  "group": "sonic",
  "types": [
   "sonic"
  ],
  "pick": false,
  "range": "Mid"
 },
 {
  "name": "Wail",
  "group": "sonic",
  "types": [
   "sonic"
  ],
  "pick": false,
  "range": "Mid"
 },
 {
  "name": "Screech",
  "group": "sonic",
  "types": [
   "sonic"
  ],
  "pick": false,
  "range": "Near"
 },
 {
  "name": "Drone",
  "group": "sonic",
  "types": [
   "sonic"
  ],
  "pick": false,
  "range": "Near"
 },
 {
  "name": "Buzzing Wings",
  "group": "sonic",
  "types": [
   "sonic"
  ],
  "pick": false,
  "range": "Near"
 },
 {
  "name": "Hiss",
  "group": "sonic",
  "types": [
   "sonic"
  ],
  "pick": false,
  "range": "Close"
 }
];
export const MONSTER_FEATS = [
 {
  "name": "Legendary Action",
  "xp": 14,
  "per": "use",
  "xpText": "14 per use",
  "requires": "any tier",
  "effect": "Immediately after an enemy ends its turn, this creature may attack that enemy, in addition to its Action and Quick Action. Once per round, or twice per round at Tier 10, up to the uses bought for each conflict."
 },
 {
  "name": "Berserk",
  "xp": 8,
  "per": "",
  "xpText": "8",
  "requires": "any tier",
  "effect": "The first time one of this creature's Attributes is Incapacitated in a conflict, its Training in its attack Skill increases by +2 for the rest of the conflict."
 },
 {
  "name": "Dread Presence",
  "xp": 12,
  "per": "",
  "xpText": "12",
  "requires": "any tier",
  "effect": "Enemies within Close range of this creature suffer -1 on Skill rolls made to Oppose it."
 },
 {
  "name": "Fatal Burst",
  "xp": 8,
  "per": "",
  "xpText": "8",
  "requires": "any tier",
  "effect": "When this creature is Destroyed, everything within Near range of it immediately takes Stress equal to this creature's Training bonus, this creature's choice of Attribute among the ones it could normally target."
 },
 {
  "name": "Undaunted",
  "xp": 24,
  "per": "",
  "xpText": "24",
  "requires": "any tier",
  "effect": "Once per round, when a Technique would apply a Condition, Weakened, or Reeling to this creature, treat the failed Oppose as a success instead: the effect fails to apply. Stress from the same Technique still lands."
 },
 {
  "name": "Specialized Immunity",
  "xp": 8,
  "per": "condition",
  "xpText": "8 per Condition",
  "requires": "any tier",
  "effect": "This creature cannot suffer one named Condition (PHB 4.2.1). Needs a stated reason: a body with no eyes cannot be Blinded, a mindless thing cannot be Charmed."
 },
 {
  "name": "Adaptive Hide",
  "xp": 12,
  "per": "",
  "xpText": "12",
  "requires": "any tier",
  "effect": "The first time in a conflict this creature takes Stress from a given Instrument Type, it gains Resistance +2 against that Instrument Type for the rest of the conflict."
 },
 {
  "name": "Pack Tactics",
  "xp": 6,
  "per": "+1",
  "xpText": "6 per +1 (max +3)",
  "requires": "any tier",
  "effect": "+1 to this creature's Techniques for each other creature bearing this same Feat within Close range, up to the bought maximum."
 },
 {
  "name": "Swarm",
  "xp": 8,
  "per": "",
  "xpText": "8",
  "requires": "any tier",
  "effect": "Area Patterns deal this creature half Stress, rounded down. This creature Opposes single-target attacks at -1."
 },
 {
  "name": "Ambush Predator",
  "xp": 8,
  "per": "",
  "xpText": "8",
  "requires": "any tier",
  "effect": "The first Technique this creature lands on a target that hasn't yet acted this conflict deals +2 additional Stress."
 },
 {
  "name": "Second Wind",
  "xp": 12,
  "per": "",
  "xpText": "12",
  "requires": "any tier",
  "effect": "The first time an Attribute of this creature's would be Incapacitated in a conflict, its Stress stops 1 short of its Potential instead."
 },
 {
  "name": "Juggernaut",
  "xp": 12,
  "per": "",
  "xpText": "12",
  "requires": "any tier",
  "effect": "The first Technique to land on this creature in a conflict deals half its Stress, rounded down."
 },
 {
  "name": "Sure-Footed",
  "xp": 8,
  "per": "",
  "xpText": "8",
  "requires": "four or more legs",
  "effect": "+2 to Oppose against any effect that would apply Prone."
 },
 {
  "name": "Wings",
  "xp": 8,
  "per": "",
  "xpText": "8",
  "requires": "wings or natural flight",
  "effect": "+2 to Oppose against any effect that would apply Grappled or Restrained."
 },
 {
  "name": "Beak",
  "xp": 8,
  "per": "",
  "xpText": "8",
  "requires": "a beak or similar Pointed natural weapon",
  "effect": "The first Technique this creature lands through that weapon each conflict gains Pierce 1."
 },
 {
  "name": "Specialized Resistance",
  "xp": 4,
  "per": "point",
  "xpText": "4 per point (damage type) or 8 per point (Family)",
  "requires": "any tier",
  "effect": "Resistance +N (PHB 6.6.0) to a single Family of Instrument Type or a single damage type (9.3.0), capped at the creature's Resistance cap (9.1.0). Needs a stated reason: a hide that turns one kind of blow, a ward tuned to one kind of dread. Stacks with whatever Broad Resistance the tier's budget (9.3.0) already bought."
 }
];
export const TRAITS = [
 {
  "name": "Fly",
  "xp": 8
 },
 {
  "name": "Swim",
  "xp": 8
 },
 {
  "name": "Burrow",
  "xp": 8
 },
 {
  "name": "Climb",
  "xp": 8
 },
 {
  "name": "Incorporeal Movement",
  "xp": 8
 },
 {
  "name": "Darkvision",
  "xp": 8
 },
 {
  "name": "Tremorsense",
  "xp": 8
 },
 {
  "name": "Blindsight, Echolocation, or Thermal Sight",
  "xp": 8
 },
 {
  "name": "Keen Scent",
  "xp": 8
 },
 {
  "name": "Web Sense",
  "xp": 8
 },
 {
  "name": "Unstoppable",
  "xp": 24
 },
 {
  "name": "True Sight",
  "xp": 16
 },
 {
  "name": "Regeneration",
  "xp": 32
 },
 {
  "name": "Rejuvenation",
  "xp": 48
 }
];
