/**
 * src/glossary-ui.js
 * Keyword help: wraps known terms in sheet text so hovering shows a short
 * definition and clicking opens it in full. Definitions come from the rulebooks
 * (src/glossary.js, generated by tools/build-glossary.mjs).
 */

import { GLOSSARY } from "./glossary.js";

// Words common enough in prose that wrapping every one would only add noise.
const SKIP = new Set(["action", "skill", "range", "price", "origin", "target", "technique", "instrument", "attribute", "training", "foil",
  "conflict", "light", "medium", "heavy", "craft", "tool", "move", "difficulty", "potential", "pattern", "instrument type", "attribute dice (ad)"]);
const ALIASES = { weaken: "weakened", reeling: "reeling", "incapacitated": "incapacitated" };

const KEYS = Object.keys(GLOSSARY).filter(k => !SKIP.has(k)).sort((a, b) => b.length - a.length);
const PATTERN = KEYS.length ? new RegExp(`\\b(${[...KEYS, ...Object.keys(ALIASES)].map(k => k.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|")})\\b`, "gi") : null;

const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/** The glossary entry for a term, or null. */
export function lookup(term) {
  const k = String(term ?? "").toLowerCase();
  return GLOSSARY[k] ?? GLOSSARY[ALIASES[k]] ?? null;
}

/** Plain text in, HTML out, with each known term wrapped. */
export function glossarize(text) {
  const src = String(text ?? "");
  if (!PATTERN) return esc(src);
  let out = "", last = 0;
  for (const m of src.matchAll(PATTERN)) {
    const entry = lookup(m[0]);
    if (!entry) continue;
    out += esc(src.slice(last, m.index))
      + `<span class="foil-term" data-term="${esc(m[0].toLowerCase())}" data-tooltip="${esc(`${entry.name}: ${entry.text}`)}">${esc(m[0])}</span>`;
    last = m.index + m[0].length;
  }
  return out + esc(src.slice(last));
}

/** Open a term's full definition. */
export function showTerm(term) {
  const entry = lookup(term);
  if (!entry) return;
  return foundry.applications.api.DialogV2.prompt({
    window: { title: entry.name }, content: `<p>${esc(entry.text)}</p>`, ok: { label: "Close" }, rejectClose: false
  }).catch(() => null);
}

/** Click handler for any element holding glossarized text. */
export function bindTerms(root) {
  root.addEventListener("click", event => {
    const el = event.target.closest?.(".foil-term");
    if (el) { event.preventDefault(); event.stopPropagation(); showTerm(el.dataset.term); }
  });
}
