/** Generated by tools/build-glossary.mjs from the PHB and Fundamental Math. Do not edit. */
export const GLOSSARY = {
  "action": {
    "name": "Action",
    "text": "The main thing a character spends each round to act or move. Most Techniques cost it."
  },
  "angered": {
    "name": "Angered",
    "text": "Resisted with Resonance or Discipline. Furious beyond talking down. It won't Flee or Yield, and keeps fighting any conflict that breaks out. It ends when it acts on the anger, or after the duration."
  },
  "attribute": {
    "name": "Attribute",
    "text": "One of four traits: Might, Finesse, Wit, or Presence. Each is a pool of dice."
  },
  "attribute dice (ad)": {
    "name": "Attribute Dice (AD)",
    "text": "The dice in an Attribute's pool. Roll them to act or to Oppose."
  },
  "baited": {
    "name": "Baited",
    "text": "Resisted with Discipline or Acuity. Fixated on the source. In conflict, it targets the source first. It ends when it acts against the source, or after the duration."
  },
  "beam": {
    "name": "Beam",
    "text": "a straight path from the caster. Reaching N bands costs the running sum 1 + 2 + ... + N."
  },
  "blinded": {
    "name": "Blinded",
    "text": "Resisted with Acuity or Discipline. The creature can't see. Its rolls take -2. Its Techniques that need line of sight reach only Touching range. It ends at the end of its next turn."
  },
  "blocking": {
    "name": "Blocking",
    "text": "Its +N applies to Oppose rolls. Guards with the Quick Action on your turn."
  },
  "blunt": {
    "name": "Blunt",
    "text": "Pierce 3 against physical Resistance."
  },
  "charmed": {
    "name": "Charmed",
    "text": "Resisted with Resonance or Acuity. The creature can't use a Technique against the source or its allies. It ends when that side deals it Stress, or after the duration."
  },
  "cone": {
    "name": "Cone",
    "text": "a 90-degree arc from the caster. Three times the Beam cost for the same reach."
  },
  "conflict": {
    "name": "Conflict",
    "text": "A contest resolved by rolling: act, Oppose, take Stress. It ends when a side Flees, Yields, or is Destroyed."
  },
  "controlled": {
    "name": "Controlled",
    "text": "Resisted with Discipline or Resonance. The source directs the creature's next turn: its movement, Skill, and target. It won't be made to harm itself. Controlled ends after that turn unless the source Upkeeps it. Each upkeep rolls again, and the creature Opposes again."
  },
  "counter": {
    "name": "Counter",
    "text": "Quick (trigger: a creature within range performs a Technique): contest it with your Skill; on a tie or better, that Technique fails. The Counter roll takes a penalty equal to that Technique's Strain"
  },
  "craft": {
    "name": "Craft",
    "text": "Its rolls are Trades working that Material, such as Craft [Metal] or Craft [Stone]. Plain Craft works any Material."
  },
  "destroyed": {
    "name": "Destroyed",
    "text": "Destruction is permanent: death, or a mind or self broken past recovering. A creature is Destroyed when all four of its Attributes are Incapacitated at the same time. Destroying an opponent is a choice."
  },
  "difficulty": {
    "name": "Difficulty",
    "text": "The number a roll must reach when no one Opposes it. The GM sets it."
  },
  "disarm": {
    "name": "Disarm",
    "text": "The target drops the Instrument it used last; picking it up costs its Quick Action, the same as switching. Innate Instruments can't be dropped"
  },
  "drain": {
    "name": "Drain",
    "text": "Deal the margin as Stress, then heal yourself for half of it (round down) on one Attribute"
  },
  "drawn": {
    "name": "Drawn",
    "text": "+2 Stress"
  },
  "edged": {
    "name": "Edged",
    "text": "+3 Stress against a physical Attribute. Physical Resistance, after Pierce, counts double against it."
  },
  "enthralled": {
    "name": "Enthralled",
    "text": "Resisted with Resonance or Discipline. Devoted to the source. The creature agrees eagerly and helps unasked. It may Oppose again to break free, with Resonance or Discipline, at each natural pause in a scene or each of its turns in a conflict. It ends when the source or an ally harms it, or the source leaves."
  },
  "evade": {
    "name": "Evade",
    "text": "Move one range band without spending the normal Disengage Quick Action and without provoking an Attack of Opportunity"
  },
  "extend range": {
    "name": "Extend Range",
    "text": "Reach one band beyond the Instrument"
  },
  "fired": {
    "name": "Fired",
    "text": "+4 Stress"
  },
  "foil": {
    "name": "FOIL",
    "text": "The Habit system: four axes, Faith, Order, Individualism, Levity. A Habit is a character's lean on one axis."
  },
  "foil exposed": {
    "name": "Foil Exposed",
    "text": "Resisted with Guile or Discipline. The source learns one Habit of the creature, which the Technique names. Once, when the creature Opposes the source, the source may give that Oppose roll -2. It ends when used, or after 10 minutes. A creature has one Foil Exposed for each of its Habits, from each source."
  },
  "foil token": {
    "name": "Foil Token",
    "text": "Earned by invoking a held Habit, spent to halve the Stress from one source or to reroll one die just rolled. A character holds at most four."
  },
  "fortifying": {
    "name": "Fortifying",
    "text": "Support, aimed at an ally or the caster."
  },
  "frightened": {
    "name": "Frightened",
    "text": "Resisted with Discipline or Resonance. While the creature can perceive the source, its rolls take -1. It can't willingly move closer to the source. It ends when the source leaves its perception or the duration ends."
  },
  "grappled": {
    "name": "Grappled",
    "text": "Resisted with Prowess or Discipline. The creature can't change range band on its own. It breaks free by spending its Action and beating the grapple's roll with Prowess or Discipline. Holding a grapple is free. The grappler moves at 1/4 speed, bringing the Grappled creature along."
  },
  "grappling": {
    "name": "Grappling",
    "text": "Adds no Stress."
  },
  "hasten": {
    "name": "Hasten",
    "text": "Grant the target an extra Action on its next turn. Holding it past that turn requires the Upkeep Effect"
  },
  "heavy": {
    "name": "Heavy",
    "text": "any Technique through it, a Quick one included, costs the Action and the Quick Action. Its margin is doubled, then capped at the full Primary Potential. It takes both hands."
  },
  "heavy instrument": {
    "name": "Heavy Instrument",
    "text": "any Technique through it, a Quick one included, costs the Action and the Quick Action. Its margin is doubled, then capped at the full Primary Potential. It takes both hands."
  },
  "illusion": {
    "name": "Illusion",
    "text": "Conjure a convincing false sight or sound. A creature that would act on the truth Opposes with Acuity to see through it; until it does, it treats the illusion as real (the GM adjudicates what it accomplishes)"
  },
  "immobile": {
    "name": "Immobile",
    "text": "+2 Stress. Fixed in place: using it means being there."
  },
  "impressed": {
    "name": "Impressed",
    "text": "Resisted with Assertiveness or Acuity. The creature grants the source's next reasonable request that doesn't work against its own interests. It ends once granted, or after the duration."
  },
  "incapacitated": {
    "name": "Incapacitated",
    "text": "An Attribute is Incapacitated when its Stress reaches its Potential. It adds no dice to any roll that draws on it. It can still be targeted. Incapacitation lifts once healing brings its Stress down to half its Potential, rounded down. Healing short of that lowers its Stress, and new Stress fills it again before overflowing. A character with an Incapacitated Attribute stays in the conflict with a full Action, Quick Action, and movement. It can use any Technique whose Skill still has dice. > [!EXAMPLE] > A creature has taken heavy damage: Might, Wit, and Presence are all Incapacitated, leaving only Finesse standing. Prowess (Might + Finesse), Acuity (Finesse + Wit), and Guile (Finesse + Presence) still roll, each on Finesse's dice alone. Discipline, Assertiveness, and Resonance are dead: neither of their Attributes has dice left, so nothing that rolls them can be attempted."
  },
  "incapacitation": {
    "name": "Incapacitation",
    "text": "One Attribute failing. Its Stress has reached its Potential, so it rolls no dice. The character stays in play."
  },
  "incorporeal": {
    "name": "Incorporeal",
    "text": "+1 Stress against a mental Attribute. -1 against a physical one."
  },
  "instrument": {
    "name": "Instrument",
    "text": "What a character acts through: a sword, a bow, a spell focus, a voice, even bare hands. Every Instrument has one Range, one Primary Attribute, and one or more Instrument Types."
  },
  "instrument type": {
    "name": "Instrument Type",
    "text": "A tag an Instrument has, such as Edged or Parry. Each one changes the Stress a landed hit deals or what the Instrument can do. This change is called a type effect."
  },
  "intimidated": {
    "name": "Intimidated",
    "text": "Resisted with Assertiveness or Resonance. On the source's next turn, it may issue one demand, which the creature obeys. First, the creature may Oppose once at -1, with Assertiveness or Resonance, to refuse. Intimidated ends when the demand is obeyed or refused, or at the end of the source's turn without one."
  },
  "invisible": {
    "name": "Invisible",
    "text": "Laid on self or an ally with no roll. Techniques against the creature take -2 and reach only Touching range. It ends when the creature uses a Technique. True Sight, Blindsight, and Keen Scent ignore it."
  },
  "kinetic": {
    "name": "Kinetic",
    "text": "+1 Stress against a physical Attribute. -1 against a mental one."
  },
  "light": {
    "name": "Light",
    "text": "its margin caps at half the Primary Potential. After the Action uses a Technique through a Light Instrument, the Quick Action can use a Light Instrument's built-in Technique."
  },
  "light instrument": {
    "name": "Light Instrument",
    "text": "its margin caps at half the Primary Potential. After the Action uses a Technique through a Light Instrument, the Quick Action can use a Light Instrument's built-in Technique."
  },
  "lines and veils": {
    "name": "Lines and Veils",
    "text": "A table agreement made before play: a Line never happens, a Veil happens but stays off-screen."
  },
  "lingering": {
    "name": "Lingering",
    "text": "The target takes N Stress at the start of its turn for two rounds; this Stress ignores Resistance"
  },
  "medium": {
    "name": "Medium",
    "text": "its margin caps at the full Primary Potential."
  },
  "medium instrument": {
    "name": "Medium Instrument",
    "text": "its margin caps at the full Primary Potential."
  },
  "mend": {
    "name": "Mend",
    "text": "Remove Xd4 Stress from one of an ally's Attributes in ten minutes, with no Medicine and no roll. A creature can be healed by Medicine, Mend, or any other removal of Stress once every 4 hours. Its user takes Strain as normal."
  },
  "misled": {
    "name": "Misled",
    "text": "Resisted with Acuity or Guile. Believes one plausible false statement from the source. It ends when given reason to doubt, or after the duration. Lasts 10 minutes by default."
  },
  "move": {
    "name": "Move",
    "text": "Push, pull, or reposition a target one range band"
  },
  "oppose": {
    "name": "Oppose",
    "text": "A roll made to resist an incoming Technique. Use any Skill built on the Attribute under attack, or a Skill the Condition names."
  },
  "origin": {
    "name": "Origin",
    "text": "The kind of place a character came from. It grants two Feats at character creation."
  },
  "overflow": {
    "name": "Overflow",
    "text": "Stress that spills onto another Attribute once the first one is full. The defender picks where it goes."
  },
  "parry": {
    "name": "Parry",
    "text": "Defends with the Quick Action when a Technique targets it, before the Oppose roll."
  },
  "pattern": {
    "name": "Pattern",
    "text": "Hit every creature in a Beam, Cone, Radius, or Wall. A Radius or Wall may be placed away from the caster."
  },
  "pierce": {
    "name": "Pierce",
    "text": "Lowers the target's Resistance against one hit, to no less than 0."
  },
  "pointed": {
    "name": "Pointed",
    "text": "+1 Stress against a physical Attribute. Pierce 1 against physical Resistance."
  },
  "potential": {
    "name": "Potential",
    "text": "The highest number an Attribute's dice can roll. It also sets how much Stress that Attribute can take before it gives out."
  },
  "price": {
    "name": "Price",
    "text": "What an item costs. 100 pennies make one silver, so 170 pennies is 1 silver and 70."
  },
  "primary attribute": {
    "name": "Primary Attribute",
    "text": "The one Attribute an Instrument is built around. It sets which three Skills can roll that Instrument."
  },
  "prone": {
    "name": "Prone",
    "text": "Resisted with Prowess or Acuity. The creature is knocked down. Its rolls take -1. Melee Techniques against it gain +1. It stands with its Quick Action."
  },
  "quick": {
    "name": "Quick",
    "text": "This Technique may be paid for with the Quick Action as well as the Action. An untagged Technique costs the Action only. The Quick Action may be spent on the user's own turn or held and spent reactively instead; a Technique may state its own trigger for reactive use inline, e.g. \"Quick (trigger: X): effect.\""
  },
  "quick action": {
    "name": "Quick Action",
    "text": "A second, smaller thing a character spends each round, on your turn or held to use reactively."
  },
  "radius": {
    "name": "Radius",
    "text": "a circle of the given size. Four times the Cone cost, twelve times the Beam, for the same size."
  },
  "range": {
    "name": "Range",
    "text": "How far an Instrument reaches: Touching, Close, Near, Short, Mid, Long, or Sight."
  },
  "redirect": {
    "name": "Redirect",
    "text": "Take an ally's incoming Stress onto yourself"
  },
  "reeling": {
    "name": "Reeling",
    "text": "Resisted with Acuity or Discipline. The creature's Oppose rolls take -N for the duration."
  },
  "relaxed": {
    "name": "Relaxed",
    "text": "Resisted with Guile or Discipline. The creature answers honestly and holds nothing back, unless that would clearly be a mistake. It ends when the source or an ally threatens or harms it."
  },
  "resistance": {
    "name": "Resistance",
    "text": "A number that lowers the Stress of every hit that lands. Physical Resistance covers Might and Finesse. Mental Resistance covers Wit and Presence."
  },
  "restrained": {
    "name": "Restrained",
    "text": "Resisted with Prowess or Discipline. The creature's Finesse is Incapacitated as long as it is Restrained and it cannot move. The Technique that applies it states how it ends."
  },
  "selective": {
    "name": "Selective",
    "text": "Choose creatures within R bands. Range is priced as an Effect, Selective adds 8 XP, and Strain is paid per target."
  },
  "skill": {
    "name": "Skill",
    "text": "One of six rolls, each made from a pair of Attributes plus Training."
  },
  "slowed": {
    "name": "Slowed",
    "text": "Resisted with Prowess or Discipline. The creature moves at half speed and can't spend its Quick Action to move farther. It loses its chase rolls. It ends at the end of its next turn."
  },
  "sonic": {
    "name": "Sonic",
    "text": "+1 Stress against a mental Attribute. -1 against a physical one."
  },
  "strain": {
    "name": "Strain",
    "text": "Stress a Technique deals its own user, on the Instrument's Primary Attribute. It ignores Resistance."
  },
  "stress": {
    "name": "Stress",
    "text": "A counter on an Attribute. It builds toward Incapacitation and caps at that Attribute's Potential. A landed hit adds Stress to the Attribute the attacker named."
  },
  "stunned": {
    "name": "Stunned",
    "text": "Resisted with Prowess or Discipline. The creature spends no Action or Quick Action. It ends at the end of its next turn."
  },
  "swayed": {
    "name": "Swayed",
    "text": "Resisted with Acuity or Resonance. Leans toward trusting and helping the source, short of acting against its own interests. Lasts 10 minutes by default."
  },
  "target": {
    "name": "Target",
    "text": "The creature or character a Technique acts against. The attacker names the Attribute it harms when they act."
  },
  "technique": {
    "name": "Technique",
    "text": "A learned ability bought with XP. It adds Effects on top of an Instrument's use."
  },
  "thrown": {
    "name": "Thrown",
    "text": "None"
  },
  "tool": {
    "name": "Tool",
    "text": "Its rolls are Trades."
  },
  "training": {
    "name": "Training",
    "text": "A flat bonus added to one Skill's rolls."
  },
  "upkeep": {
    "name": "Upkeep",
    "text": "Keeps a Technique working each turn. Pay its Action or Quick Action and its Strain again."
  },
  "wall": {
    "name": "Wall",
    "text": "a straight barrier of the given length, placed and oriented freely. Same cost as a Beam of that length."
  },
  "wary": {
    "name": "Wary",
    "text": "Laid on an ally with no roll. On guard against a named creature. An ally with Wary won't take that creature's word, advice, or request without confirming it. It ends when the caster says so, or after the duration."
  },
  "weakened": {
    "name": "Weakened",
    "text": "Resisted with any Skill built on the named Attribute. The named Attribute's rolls take -N for the duration. Instances stack, each tracked separately."
  }
};
